### ISSUE TITLE
vsce package

### ISSUE THREAD

**Issue by bsed** [jonathandturner/rls_vscode#62]
kelvin@gnux:~/rls_vscode> vsce package
Executing prepublish script 'npm run vscode:prepublish'...
Error: Command failed: npm run vscode:prepublish
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! rls-vscode@0.0.1 vscode:prepublish: `tsc -p ./`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the rls-vscode@0.0.1 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kelvin/.npm/_logs/2017-06-17T08_06_39_393Z-debug.log

**Comment by bsed** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/kelvin/.nvm/versions/node/v8.1.2/bin/node',
1 verbose cli   '/home/kelvin/.nvm/versions/node/v8.1.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'vscode:prepublish' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose run-script [ 'prevscode:prepublish',
4 verbose run-script   'vscode:prepublish',
4 verbose run-script   'postvscode:prepublish' ]
5 info lifecycle rls-vscode@0.0.1~prevscode:prepublish: rls-vscode@0.0.1
6 silly lifecycle rls-vscode@0.0.1~prevscode:prepublish: no script for prevscode:prepublish, continuing
7 info lifecycle rls-vscode@0.0.1~vscode:prepublish: rls-vscode@0.0.1
8 verbose lifecycle rls-vscode@0.0.1~vscode:prepublish: unsafe-perm in lifecycle true
9 verbose lifecycle rls-vscode@0.0.1~vscode:prepublish: PATH: /home/kelvin/.nvm/versions/node/v8.1.2/lib/node_modules/npm/bin/node-gyp-bin:/home/kelvin/rls_vscode/node_modules/.bin:/home/kelvin/.linuxbrew/bin:/home/kelvinw/.cabal/bin:/home/kelvin/.nvm/versions/node/v8.1.2/bin:/home/kelvin/bin:/home/kelvin/ruby:/opt/bin:/usr/local/bin:/usr/local/share/python:/home/kelvin/gocode/bin:/usr/local/opt/go/libexec/bin:/home/kelvin/Qt5.7/5.7/gcc_64/bin/:/home/kelvin/.cargo/bin:/opt/tools/jdk/jdk1.8.0_121/bin://opt/tools/jdk/jdk1.8.0_121/jre/bin:/home/kelvin/.cargo/bin:/home/kelvin/.rvm/gems/ruby-2.4.0/bin:/home/kelvin/.rvm/gems/ruby-2.4.0@global/bin:/home/kelvin/.rvm/rubies/ruby-2.4.0/bin:/home/kelvin/.local/bin:/home/kelvin/bin:/home/kelvin/tools/maven/bin:/opt/tools/jdk/jdk1.8.0_121/bin://opt/tools/jdk/jdk1.8.0_121/jre/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/kelvin/.rvm/bin:/home/kelvin/.rvm/bin:/home/kelvin/gocode/bin:/home/kelvin/go/bin:/home/kelvin/tools/android/adt-bundle-linux-x86_64-20140702/sdk//tools:/home/kelvin/tools/android/adt-bundle-linux-x86_64-20140702/sdk//platform-tools:/opt/gradle/gradle-3.5/bin:/home/kelvin/.rvm/bin:/home/kelvin/.rvm/bin:/home/kelvin/.vim/plugged/fzf/bin
10 verbose lifecycle rls-vscode@0.0.1~vscode:prepublish: CWD: /home/kelvin/rls_vscode
11 silly lifecycle rls-vscode@0.0.1~vscode:prepublish: Args: [ '-c', 'tsc -p ./' ]
12 silly lifecycle rls-vscode@0.0.1~vscode:prepublish: Returned: code: 2  signal: null
13 info lifecycle rls-vscode@0.0.1~vscode:prepublish: Failed to exec vscode:prepublish script
14 verbose stack Error: rls-vscode@0.0.1 vscode:prepublish: `tsc -p ./`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/home/kelvin/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/kelvin/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid rls-vscode@0.0.1
16 verbose cwd /home/kelvin/rls_vscode
17 verbose Linux 4.10.0-22-generic
18 verbose argv "/home/kelvin/.nvm/versions/node/v8.1.2/bin/node" "/home/kelvin/.nvm/versions/node/v8.1.2/bin/npm" "run" "vscode:prepublish"
19 verbose node v8.1.2
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 2
23 error rls-vscode@0.0.1 vscode:prepublish: `tsc -p ./`
23 error Exit status 2
24 error Failed at the rls-vscode@0.0.1 vscode:prepublish script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 2, true ]
```

**Comment by jonasbb** [comment]
I don't see any compiler error messages here, so this could be https://github.com/jonathandturner/rls_vscode/issues/60. In this case just run `npm install` first.

**Comment by bsed** [comment]
i have run` npm install` set node memsize

**Comment by bsed** [comment]
The same operation steps, I again ubuntu17.10 (7.7G) hold this kind of mistake, windows 10 (16G) does not have this kind of problem.
window10:
```
feng@fengpc MINGW32 /e/workspace/nodejs/rls_vscode (master)
$ npm install
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> rls-vscode@0.0.1 postinstall E:\workspace\nodejs\rls_vscode
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.8.0
Found minimal version that qualifies engine range: 1.8.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/1.8.0/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN rls-vscode@0.0.1 No license field.

added 313 packages in 27.076s

feng@fengpc MINGW32 /e/workspace/nodejs/rls_vscode (master)
$ npm install -g vsce
E:\nodejs\vsce -> E:\nodejs\node_modules\vsce\out\vsce
added 35 packages in 4.398s

feng@fengpc MINGW32 /e/workspace/nodejs/rls_vscode (master)

$ vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> rls-vscode@0.0.1 vscode:prepublish E:\workspace\nodejs\rls_vscode
> tsc -p ./

Created: E:\workspace\nodejs\rls_vscode\rls-vscode-0.0.1.vsix

feng@fengpc MINGW32 /e/workspace/nodejs/rls_vscode (master)
```

**Comment by bsed** [comment]
I think it may be incompatible with the system. At the same time, I have decided to turn this problem off. Thank you

**Comment by bsed** [comment]
vsix download: https://github.com/bsed/rls-vscode/blob/master/rls-vscode-0.0.1.vsix
